from __future__ import unicode_literals

PERMISSION_ADMIN = 'admin'
PERMISSION_STAFF = 'staff'
PERMISSION_USER = 'user'
PERMISSION_CHOICES = (
    (PERMISSION_ADMIN, 'Admin'),
    (PERMISSION_USER, 'User'),
    (PERMISSION_STAFF, 'Staff'),
)
PERMISSIONS_SUPERUSER_ONLY = []
PERMISSIONS_ADMIN_ONLY = [PERMISSION_ADMIN]
PERMISSIONS_STAFF_AND_ABOVE = [PERMISSION_ADMIN, PERMISSION_STAFF]
PERMISSIONS_USER_AND_ABOVE = [PERMISSION_ADMIN, PERMISSION_STAFF,
                              PERMISSION_USER]
